### ISSUE TITLE
[question] What is the difference between BasicNN and BasicNeuralNet?

### ISSUE THREAD

**Issue by mtanneau** [AI4OPT/ML4OPF#22]
I see that some `ml4opf/models` classes are called `<prefix>BasicNN` and others `<prefix>BasicNeuralNet`.

It is not clear to me what the difference is, and whether I should use one over the other.
For reference:
* The class `BasicNeuralNet` is defined here
  https://github.com/AI4OPT/ML4OPF/blob/5e0705d78a6e9751c9153bf006a88bbfdfa2702a/ml4opf/models/basic_nn/basic_nn.py#L11
* The class `BasicNN` seems to be linked to pytorch-lightning; it is defined here:
  https://github.com/AI4OPT/ML4OPF/blob/5e0705d78a6e9751c9153bf006a88bbfdfa2702a/ml4opf/models/basic_nn/lightning_basic_nn.py#L13

Child classes are then defined for specific OPF formulations. For instance, for ACOPF, we have `ACBasicNN` and `ACBasicNeuralNet`

**Comment by klamike** [comment]
`BasicNeuralNet` is a wrapper around `BasicNN`, which is where the actual torch model implementation happens.

I've been considering merging them since you almost always need to subclass both when implementing a new model. The main concern is clashes between the `OPFModel` API and the `pl.LightningModule` methods.

In most cases (when using problem-default datasets), you only have to implement the `predict` method in children of `BasicNeuralNet` and typehint what `BasicNN` child it should wrap. If you change the dataset, you may want to implement a new `BasicNeuralNet.evaluate_model` as well.
